[package]
name = "rdedup"
version = "0.1.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Data deduplication with compression and public key encryption. - binary"
keywords = ["data", "backup", "dedupliation", "encryption", "dedup"]
license = "CFSF-v0"
documentation = "https://dpc.github.io/rdedup-lib/"
homepage = "https://github.com/dpc/rdedup"
repository = "https://github.com/dpc/rdedup"
readme = "README.md"
exclude = ["lib/**/*"]

[[bin]]
name = "rdedup"
path = "src/bin.rs"

[dependencies]
rdedup-lib = { version = "0.1.0", path = "lib" }
log = "0.3.6"
rustc-serialize = "0.3.19"
argparse = "0.2.1"
env_logger = "0.3.3"
